// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class FirebaseRestOptions {
  const FirebaseRestOptions({
    required this.apiKey,
    required this.appId,
    required this.messagingSenderId,
    required this.projectId,
    required this.databaseURL,
    this.authDomain,
    this.storageBucket,
    this.iosBundleId,
    this.measurementId,
  });

  final String apiKey;
  final String appId;
  final String messagingSenderId;
  final String projectId;
  final String databaseURL;
  final String? authDomain;
  final String? storageBucket;
  final String? iosBundleId;
  final String? measurementId;
}

/// Default Firebase REST configuration for the app.
class DefaultFirebaseOptions {
  static FirebaseRestOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseRestOptions macos = FirebaseRestOptions(
    apiKey: 'AIzaSyCLamxvGAMLVVICWrbdD_paDVmQCZpZJCg',
    appId: '1:920135500112:ios:c23f1c8915caa07c2f2c55',
    messagingSenderId: '920135500112',
    projectId: 'ngo-management-system-d8c06',
    databaseURL:
        'https://ngo-management-system-d8c06-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ngo-management-system-d8c06.firebasestorage.app',
    iosBundleId: 'com.example.ngo',
  );

  static const FirebaseRestOptions windows = FirebaseRestOptions(
    apiKey: 'AIzaSyCLamxvGAMLVVICWrbdD_paDVmQCZpZJCg',
    appId: '1:920135500112:web:7e1312a89809b48a2f2c55',
    messagingSenderId: '920135500112',
    projectId: 'ngo-management-system-d8c06',
    authDomain: 'ngo-management-system-d8c06.firebaseapp.com',
    databaseURL:
        'https://ngo-management-system-d8c06-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ngo-management-system-d8c06.firebasestorage.app',
    measurementId: 'G-67SZ7ZHM4K',
  );
}
